name: Snake
on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"
jobs:
  Snake:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: generate-snake-game-from-github-contribution-grid
        uses: Platane/snk@v3.3.0
        with:
          github_user_name: guadaaaaa
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark&color_snake=yellow&color_dots=#13243e,#003997,#4a61d8,#adcbf0,#ffffff
            dist/ocean.gif?color_snake=yellow&color_dots=#161b22,#39c4dd,#ceecff,#a3e1ed,#ffffff

      - name: Push files to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
